# Generated by Django 4.0.1 on 2022-01-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_image_product_product_category_product_collection'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='_id',
            new_name='id',
        ),
    ]
