# Generated by Django 4.0.1 on 2022-01-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, default='/default.webp', null=True, upload_to=''),
        ),
    ]
