# Generated by Django 4.0.1 on 2022-02-05 17:22

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_color_href_color_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='name',
            field=models.CharField(default='Noir', max_length=50),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.CharField(default='#000000', max_length=7, unique=True, validators=[base.models.validate_hex]),
        ),
    ]
