# Generated by Django 4.0.1 on 2022-01-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_order_shippingaddress_orderproduct_billingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='path',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
