# Generated by Django 4.0.1 on 2022-01-21 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inStock',
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='base.product'),
        ),
    ]
