# Generated by Django 4.0.1 on 2022-01-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_product_instock_alter_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='product',
            name='quantityInStock',
            field=models.IntegerField(default=1),
        ),
    ]
